<a href="https://colab.research.google.com/github/cannin/gsoc_2023_pytorch_pathway_commons/blob/main/Notebooks/acc_data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
!wget https://zenodo.org/record/8286179/files/data_clinical_patient.txt?download=1 -O data_clinical_patient.txt

--2023-08-28 14:03:18--  https://zenodo.org/record/8286179/files/data_clinical_patient.txt?download=1
Resolving zenodo.org (zenodo.org)... 188.185.124.72
Connecting to zenodo.org (zenodo.org)|188.185.124.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31230 (30K) [text/plain]
Saving to: ‘data_clinical_patient.txt’

data_clinical_patie 100%[===================>]  30.50K  --.-KB/s    in 0s

2023-08-28 14:03:19 (368 MB/s) - ‘data_clinical_patient.txt’ saved [31230/31230]

In [3]:
!wget https://zenodo.org/record/8286179/files/data_clinical_sample.txt?download=1  -O data_clinical_sample.txt

--2023-08-28 14:03:19--  https://zenodo.org/record/8286179/files/data_clinical_sample.txt?download=1
Resolving zenodo.org (zenodo.org)... 188.185.124.72
Connecting to zenodo.org (zenodo.org)|188.185.124.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21056 (21K) [text/plain]
Saving to: ‘data_clinical_sample.txt’

data_clinical_sampl 100%[===================>]  20.56K  --.-KB/s    in 0s

2023-08-28 14:03:19 (182 MB/s) - ‘data_clinical_sample.txt’ saved [21056/21056]

In [4]:
!wget https://zenodo.org/record/8286179/files/data_mrna_seq_v2_rsem.txt?download=1 -O data_mrna_seq_v2_rsem.txt

--2023-08-28 14:03:19--  https://zenodo.org/record/8286179/files/data_mrna_seq_v2_rsem.txt?download=1
Resolving zenodo.org (zenodo.org)... 188.185.124.72
Connecting to zenodo.org (zenodo.org)|188.185.124.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11070320 (11M) [text/plain]
Saving to: ‘data_mrna_seq_v2_rsem.txt’

data_mrna_seq_v2_rs 100%[===================>]  10.56M  2.23MB/s    in 4.7s

2023-08-28 14:03:25 (2.23 MB/s) - ‘data_mrna_seq_v2_rsem.txt’ saved [11070320/11070320]

In [5]:
!wget https://zenodo.org/record/8251328/files/PathwayCommons12.reactome.hgnc.sif.gz?download=1 -O PathwayCommons12.reactome.hgnc.sif.gz

--2023-08-28 14:03:25--  https://zenodo.org/record/8251328/files/PathwayCommons12.reactome.hgnc.sif.gz?download=1
Resolving zenodo.org (zenodo.org)... 188.185.124.72
Connecting to zenodo.org (zenodo.org)|188.185.124.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1231249 (1.2M) [application/octet-stream]
Saving to: ‘PathwayCommons12.reactome.hgnc.sif.gz’

PathwayCommons12.re 100%[===================>]   1.17M  2.69MB/s    in 0.4s

2023-08-28 14:03:26 (2.69 MB/s) - ‘PathwayCommons12.reactome.hgnc.sif.gz’ saved [1231249/1231249]

# Handling the cBIo Data

In [ ]:
data_sample = pd.read_csv("data_clinical_sample.txt", sep="\t")

In [ ]:
data_sample.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Neoplasm Histologic Grade,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,Sample Type,MSI MANTIS Score,MSIsensor Score,Somatic Status,TMB (nonsynonymous),Tissue Source Site
0,#Identifier to uniquely specify a patient.,A unique sample identifier.,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Numeric value to express the degree of abnorma...,Tissue prospective collection indicator.,Tissue retrospective collection indicator.,Tissue Source Site Code,Text term that describes the anatomic site of ...,Aneuploidy Score,"The type of sample (i.e., normal, primary, met...",MSI Score reported by MANTIS. The suggested th...,MSI Score reported by MSIsensor. The suggested...,Somatic Status,TMB (nonsynonymous),"A Tissue Source Site collects samples (tissue,..."
1,#STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,NUMBER,STRING,NUMBER,NUMBER,STRING,NUMBER,STRING
2,#1,1,1,1,1,1,1,1,1,1,1,1,9,9,9,1,1,1
3,PATIENT_ID,SAMPLE_ID,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,TUMOR_TYPE,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TISSUE_SOURCE_SITE_CODE,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,SOMATIC_STATUS,TMB_NONSYNONYMOUS,TISSUE_SOURCE_SITE
4,TCGA-OR-A5J1,TCGA-OR-A5J1-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,2,Primary,0.275,0,Matched,0.8,University of Michigan

In [ ]:
ds1 = data_sample.drop([0,1,2,3])
ds1.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Neoplasm Histologic Grade,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,Sample Type,MSI MANTIS Score,MSIsensor Score,Somatic Status,TMB (nonsynonymous),Tissue Source Site
4,TCGA-OR-A5J1,TCGA-OR-A5J1-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,2,Primary,0.275,0,Matched,0.8,University of Michigan
5,TCGA-OR-A5J2,TCGA-OR-A5J2-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,10,Primary,0.3236,1.57,Matched,0.966666667,University of Michigan
6,TCGA-OR-A5J3,TCGA-OR-A5J3-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,12,Primary,0.3434,1.82,Matched,0.333333333,University of Michigan
7,TCGA-OR-A5J4,TCGA-OR-A5J4-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,17,Primary,0.2997,0.45,Matched,3.866666667,University of Michigan
8,TCGA-OR-A5J5,TCGA-OR-A5J5-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,33,Primary,0.5224,5.38,Matched,11.86666667,University of Michigan

In [ ]:
ds1.shape

(92, 18)

In [ ]:
ds1.isnull().sum()

#Patient Identifier                           0
Sample Identifier                             0
Oncotree Code                                 0
Cancer Type                                   0
Cancer Type Detailed                          0
Tumor Type                                    0
Neoplasm Histologic Grade                    92
Tissue Prospective Collection Indicator       0
Tissue Retrospective Collection Indicator     0
Tissue Source Site Code                       0
Tumor Disease Anatomic Site                   0
Aneuploidy Score                              3
Sample Type                                   0
MSI MANTIS Score                              1
MSIsensor Score                               1
Somatic Status                                0
TMB (nonsynonymous)                           1
Tissue Source Site                            0
dtype: int64

In [ ]:
cleaned_ds = ds1.dropna(axis=1, how='all')
cleaned_ds.isnull().sum()

#Patient Identifier                          0
Sample Identifier                            0
Oncotree Code                                0
Cancer Type                                  0
Cancer Type Detailed                         0
Tumor Type                                   0
Tissue Prospective Collection Indicator      0
Tissue Retrospective Collection Indicator    0
Tissue Source Site Code                      0
Tumor Disease Anatomic Site                  0
Aneuploidy Score                             3
Sample Type                                  0
MSI MANTIS Score                             1
MSIsensor Score                              1
Somatic Status                               0
TMB (nonsynonymous)                          1
Tissue Source Site                           0
dtype: int64

In [ ]:
cleaned_ds = cleaned_ds.fillna(method='ffill')

In [ ]:
cleaned_ds = cleaned_ds.drop(columns='Cancer Type')

In [ ]:
data_patient = pd.read_csv("data_clinical_patient.txt", sep="\t")

In [ ]:
dcp = data_patient.drop([0,1,2,3])
dcp.head()

,#Patient Identifier,Subtype,TCGA PanCanAtlas Cancer Type Acronym,Other Patient ID,Diagnosis Age,Sex,Neoplasm Disease Stage American Joint Committee on Cancer Code,American Joint Committee on Cancer Publication Version Type,Last Communication Contact from Initial Pathologic Diagnosis Date,Birth from Initial Pathologic Diagnosis Date,...,Patient Weight,In PanCan Pathway Analysis,Overall Survival Status,Overall Survival (Months),Disease-specific Survival status,Months of disease-specific survival,Disease Free Status,Disease Free (Months),Progression Free Status,Progress Free Survival (Months)
4,TCGA-OR-A5J1,ACC,ACC,B3164F7B-C826-4E08-9EE6-8FF96D29B913,58,Male,STAGE II,NaN,NaN,-21496,...,NaN,Yes,1:DECEASED,44.54745701,1:DEAD WITH TUMOR,44.54745701,1:Recurred/Progressed,24.78876944,1:PROGRESSION,24.78876944
5,TCGA-OR-A5J2,ACC,ACC,8E7C2E31-D085-4B75-A970-162526DD07A0,44,Female,STAGE IV,NaN,NaN,-16090,...,NaN,Yes,1:DECEASED,55.13364237,1:DEAD WITH TUMOR,55.13364237,NaN,NaN,1:PROGRESSION,9.50126574
6,TCGA-OR-A5J3,ACC,ACC,DFD687BC-6E69-42F7-AF94-D17FC150D1A1,23,Female,STAGE III,NaN,2091,-8624,...,NaN,Yes,0:LIVING,68.74445212,0:ALIVE OR DEAD TUMOR FREE,68.74445212,1:Recurred/Progressed,1.742446658,1:PROGRESSION,1.742446658
7,TCGA-OR-A5J4,NaN,ACC,5F3E2974-F1DF-47A2-8A8A-29BB525EEEF6,23,Female,STAGE IV,NaN,NaN,-8451,...,NaN,No,1:DECEASED,13.90669691,1:DEAD WITH TUMOR,13.90669691,NaN,NaN,1:PROGRESSION,4.142420357
8,TCGA-OR-A5J5,ACC,ACC,802DBD0D-EF07-4C91-AB8D-1DD39532E947,30,Male,STAGE III,NaN,NaN,-11171,...,NaN,Yes,1:DECEASED,11.9998685,1:DEAD WITH TUMOR,11.9998685,NaN,NaN,1:PROGRESSION,1.643817602

In [ ]:
dcp.isnull().sum()

#Patient Identifier                                                                             0
Subtype                                                                                        16
TCGA PanCanAtlas Cancer Type Acronym                                                            0
Other Patient ID                                                                                0
Diagnosis Age                                                                                   0
Sex                                                                                             0
Neoplasm Disease Stage American Joint Committee on Cancer Code                                  2
American Joint Committee on Cancer Publication Version Type                                    92
Last Communication Contact from Initial Pathologic Diagnosis Date                              31
Birth from Initial Pathologic Diagnosis Date                                                    0
Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value                          0
Ethnicity Category                                                                             44
Form completion date                                                                            0
Neoadjuvant Therapy Type Administered Prior To Resection Text                                   0
ICD-10 Classification                                                                           0
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code     0
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code          0
Informed consent verified                                                                       0
New Neoplasm Event Post Initial Therapy Indicator                                               9
American Joint Committee on Cancer Metastasis Stage Code                                       92
Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code                       2
American Joint Committee on Cancer Tumor Stage Code                                             2
Person Neoplasm Cancer Status                                                                   2
Primary Lymph Node Presentation Assessment                                                     17
Prior Diagnosis                                                                                 0
Race Category                                                                                  11
Radiation Therapy                                                                               3
Patient Weight                                                                                 92
In PanCan Pathway Analysis                                                                      0
Overall Survival Status                                                                         1
Overall Survival (Months)                                                                       1
Disease-specific Survival status                                                                3
Months of disease-specific survival                                                             1
Disease Free Status                                                                            39
Disease Free (Months)                                                                          39
Progression Free Status                                                                         1
Progress Free Survival (Months)                                                                 1
dtype: int64

In [ ]:
dcp['Overall Survival (Months)'] = dcp['Overall Survival (Months)'].fillna(method='ffill')

In [ ]:
dcp = dcp.dropna(how='any', axis=1)

In [ ]:
merged_df = pd.merge(cleaned_ds, dcp, on='#Patient Identifier') #merging the two datasets on the identifier column

In [ ]:
merged_df.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type Detailed,Tumor Type,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,...,Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value,Form completion date,Neoadjuvant Therapy Type Administered Prior To Resection Text,ICD-10 Classification,"International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code","International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code",Informed consent verified,Prior Diagnosis,In PanCan Pathway Analysis,Overall Survival (Months)
0,TCGA-OR-A5J1,TCGA-OR-A5J1-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,2,...,0,4/2/14,No,C74.0,8370/1,C74.0,Yes,No,Yes,44.54745701
1,TCGA-OR-A5J2,TCGA-OR-A5J2-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,10,...,0,12/3/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,55.13364237
2,TCGA-OR-A5J3,TCGA-OR-A5J3-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,12,...,0,12/2/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,68.74445212
3,TCGA-OR-A5J4,TCGA-OR-A5J4-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,17,...,0,12/2/13,No,C74.0,8370/3,C74.0,Yes,No,No,13.90669691
4,TCGA-OR-A5J5,TCGA-OR-A5J5-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,33,...,0,12/3/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,11.9998685

In [ ]:
merged_df.columns

Index(['#Patient Identifier', 'Sample Identifier', 'Oncotree Code',
       'Cancer Type Detailed', 'Tumor Type',
       'Tissue Prospective Collection Indicator',
       'Tissue Retrospective Collection Indicator', 'Tissue Source Site Code',
       'Tumor Disease Anatomic Site', 'Aneuploidy Score', 'Sample Type',
       'MSI MANTIS Score', 'MSIsensor Score', 'Somatic Status',
       'TMB (nonsynonymous)', 'Tissue Source Site',
       'TCGA PanCanAtlas Cancer Type Acronym', 'Other Patient ID',
       'Diagnosis Age', 'Sex', 'Birth from Initial Pathologic Diagnosis Date',
       'Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value',
       'Form completion date',
       'Neoadjuvant Therapy Type Administered Prior To Resection Text',
       'ICD-10 Classification',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
       'Informed consent verified', 'Prior Diagnosis',
       'In PanCan Pathway Analysis', 'Overall Survival (Months)'],
      dtype='object')

In [ ]:
# Assuming your DataFrame is named 'df'
columns_to_keep = ['#Patient Identifier', 'Sample Identifier', 'Overall Survival (Months)']
used_df = merged_df[columns_to_keep]   #dropping every column except the identifiers and the column to predict

In [ ]:
used_df.head()

  #Patient Identifier Sample Identifier Overall Survival (Months)
0        TCGA-OR-A5J1   TCGA-OR-A5J1-01               44.54745701
1        TCGA-OR-A5J2   TCGA-OR-A5J2-01               55.13364237
2        TCGA-OR-A5J3   TCGA-OR-A5J3-01               68.74445212
3        TCGA-OR-A5J4   TCGA-OR-A5J4-01               13.90669691
4        TCGA-OR-A5J5   TCGA-OR-A5J5-01                11.9998685

In [ ]:
used_df.shape

(92, 3)

In [ ]:
df = pd.read_csv("data_mrna_seq_v2_rsem.txt", sep="\t")

In [ ]:
patients = df.copy()
patients.head()

,Hugo_Symbol,Entrez_Gene_Id,TCGA-OR-A5J1-01,TCGA-OR-A5J2-01,TCGA-OR-A5J3-01,TCGA-OR-A5J5-01,TCGA-OR-A5J6-01,TCGA-OR-A5J7-01,TCGA-OR-A5J8-01,TCGA-OR-A5J9-01,...,TCGA-OR-A5LR-01,TCGA-OR-A5LS-01,TCGA-OR-A5LT-01,TCGA-OU-A5PI-01,TCGA-P6-A5OF-01,TCGA-PA-A5YG-01,TCGA-PK-A5H8-01,TCGA-PK-A5H9-01,TCGA-PK-A5HA-01,TCGA-PK-A5HB-01
0,NUDT18,79873,85.0144,165.884,309.2880,178.931,124.0660,283.5940,283.4650,123.7530,...,154.8120,176.1820,177.7210,157.925,524.4430,316.228,317.3020,232.0510,303.749,159.9840
1,SHC3,53358,97.5024,92.605,10.0726,49.574,5.5886,50.9426,36.0547,73.0957,...,46.0251,33.2035,75.6803,22.805,24.2472,113.731,46.8457,0.6979,192.944,50.5213
2,NCRNA00112,54089,0.0000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.000,0.0000,0.000,0.0000,0.0000,0.000,0.0000
3,FAM49B,51571,671.9500,812.911,482.2990,466.305,1074.6800,594.4650,938.6660,592.9260,...,884.5190,272.4040,326.5310,263.398,931.5600,748.960,1241.1000,784.4370,897.464,718.9250
4,FMO6P,388714,0.0000,0.000,0.0000,0.000,0.0000,0.0000,0.4144,0.0000,...,0.0000,0.0000,0.0000,0.000,0.0000,0.000,0.0000,0.0000,0.000,0.4010

In [ ]:
patients = patients.drop('Entrez_Gene_Id', axis=1)

In [ ]:
patients.shape

(20531, 79)

In [ ]:
patients.isnull().sum()

Hugo_Symbol        13
TCGA-OR-A5J1-01     0
TCGA-OR-A5J2-01     0
TCGA-OR-A5J3-01     0
TCGA-OR-A5J5-01     0
                   ..
TCGA-PA-A5YG-01     0
TCGA-PK-A5H8-01     0
TCGA-PK-A5H9-01     0
TCGA-PK-A5HA-01     0
TCGA-PK-A5HB-01     0
Length: 79, dtype: int64

In [ ]:
patients = patients.dropna()

In [ ]:
identifiers = patients['Hugo_Symbol'].unique()
print(len(identifiers))

20511

In [ ]:
# Check for duplicate 'Hugo_Symbol' values
duplicates = patients['Hugo_Symbol'].duplicated(keep='last')

# Drop rows with duplicate 'Hugo_Symbol' or same symbol as the previous row
new_df = patients[~duplicates]

# Verify the updated DataFrame shape
print(new_df.shape)

(20511, 79)

In [ ]:
new_df_transposed = new_df.set_index('Hugo_Symbol').transpose()
new_df_transposed.head()

Hugo_Symbol,NUDT18,SHC3,NCRNA00112,FAM49B,FMO6P,BAT2L2,SIRT1,MSLNL,ATG4A,ESPN,...,SCARNA6,SNORD77,TLR10,GKN2,PCDHGB4,ZMAT5,AXIN2,LONRF1,KLHL10,C12orf36
TCGA-OR-A5J1-01,85.0144,97.5024,0.0,671.950,0.0,2428.43,462.056,0.0,385.687,20.1729,...,0.0000,0.0,12.0077,0.0,17.2911,913.535,547.5500,363.112,1.9212,0.0
TCGA-OR-A5J2-01,165.8840,92.6050,0.0,812.911,0.0,5097.30,669.977,0.0,547.980,2.8184,...,0.4026,0.0,0.8053,0.0,268.9890,303.978,1793.3200,592.672,0.0000,0.0
TCGA-OR-A5J3-01,309.2880,10.0726,0.0,482.299,0.0,1615.76,514.294,0.0,1125.170,38.5128,...,0.5925,0.0,0.0000,0.0,689.4860,324.592,522.5890,456.821,0.0000,0.0
TCGA-OR-A5J5-01,178.9310,49.5740,0.0,466.305,0.0,1202.17,591.789,0.0,525.949,10.8443,...,0.0000,0.0,6.9713,0.0,54.2215,790.550,337.7230,484.895,1.5492,0.0
TCGA-OR-A5J6-01,124.0660,5.5886,0.0,1074.680,0.0,1424.53,805.312,0.0,279.987,3.9120,...,1.6766,0.0,1.1177,0.0,8.9417,291.550,9.5006,628.155,1.1177,0.0

In [ ]:
# Merge the datasets based on the patient identifiers
patient_df = pd.merge(used_df, new_df_transposed, left_on='Sample Identifier', right_index=True)

In [ ]:
patient_df.shape

(78, 20514)

In [ ]:
patient_df = patient_df.drop('#Patient Identifier', axis=1)

In [ ]:
patient_df.set_index('Sample Identifier')

,Overall Survival (Months),NUDT18,SHC3,NCRNA00112,FAM49B,FMO6P,BAT2L2,SIRT1,MSLNL,ATG4A,...,SCARNA6,SNORD77,TLR10,GKN2,PCDHGB4,ZMAT5,AXIN2,LONRF1,KLHL10,C12orf36
Sample Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-OR-A5J1-01,44.54745701,85.0144,97.5024,0.0,671.950,0.000,2428.43,462.056,0.0000,385.687,...,0.0000,0.0,12.0077,0.000,17.2911,913.535,547.5500,363.112,1.9212,0.0
TCGA-OR-A5J2-01,55.13364237,165.8840,92.6050,0.0,812.911,0.000,5097.30,669.977,0.0000,547.980,...,0.4026,0.0,0.8053,0.000,268.9890,303.978,1793.3200,592.672,0.0000,0.0
TCGA-OR-A5J3-01,68.74445212,309.2880,10.0726,0.0,482.299,0.000,1615.76,514.294,0.0000,1125.170,...,0.5925,0.0,0.0000,0.000,689.4860,324.592,522.5890,456.821,0.0000,0.0
TCGA-OR-A5J5-01,11.9998685,178.9310,49.5740,0.0,466.305,0.000,1202.17,591.789,0.0000,525.949,...,0.0000,0.0,6.9713,0.000,54.2215,790.550,337.7230,484.895,1.5492,0.0
TCGA-OR-A5J6-01,88.86477956,124.0660,5.5886,0.0,1074.680,0.000,1424.53,805.312,0.0000,279.987,...,1.6766,0.0,1.1177,0.000,8.9417,291.550,9.5006,628.155,1.1177,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-PA-A5YG-01,24.85452214,316.2280,113.7310,0.0,748.960,0.000,1779.01,876.098,0.0000,732.316,...,0.0000,0.0,9.2464,0.000,780.8410,431.114,611.6500,657.420,0.4623,0.0
TCGA-PK-A5H8-01,119.1110234,317.3020,46.8457,0.0,1241.100,0.000,1908.81,492.192,0.6246,505.934,...,0.0000,0.0,4.9969,0.000,98.8445,250.462,62.4610,450.344,0.0000,0.0
TCGA-PK-A5H9-01,20.25183286,232.0510,0.6979,0.0,784.437,0.000,2699.82,756.870,0.0000,329.757,...,0.0000,0.0,2.0937,0.000,15.0048,249.987,45.7123,239.379,1.0468,0.0
TCGA-PK-A5HA-01,39.4844988,303.7490,192.9440,0.0,897.464,0.000,2393.05,732.084,0.0000,1101.980,...,0.5513,0.0,3.3076,0.000,1086.8500,247.393,192.3930,672.547,0.5513,0.0
TCGA-PK-A5HB-01,42.50912319,159.9840,50.5213,0.0,718.925,0.401,3359.26,1462.710,0.4010,884.523,...,0.0000,0.0,15.6375,0.401,94.2261,314.836,33.2799,121.091,0.4010,0.0

In [ ]:
cBio = pd.DataFrame(patient_df)

In [ ]:
cBio.to_csv('cBio.csv', index=False)  #converting to csv to save the new dataset

In [ ]:
cBio = cBio.set_index('Sample Identifier')
cBio.index.name = None
cBio.head(2)

,Overall Survival (Months),NUDT18,SHC3,NCRNA00112,FAM49B,FMO6P,BAT2L2,SIRT1,MSLNL,ATG4A,...,SCARNA6,SNORD77,TLR10,GKN2,PCDHGB4,ZMAT5,AXIN2,LONRF1,KLHL10,C12orf36
TCGA-OR-A5J1-01,44.54745701,85.0144,97.5024,0.0,671.950,0.0,2428.43,462.056,0.0,385.687,...,0.0000,0.0,12.0077,0.0,17.2911,913.535,547.55,363.112,1.9212,0.0
TCGA-OR-A5J2-01,55.13364237,165.8840,92.6050,0.0,812.911,0.0,5097.30,669.977,0.0,547.980,...,0.4026,0.0,0.8053,0.0,268.9890,303.978,1793.32,592.672,0.0000,0.0

In [ ]:
#splitting the created dataset to features and lables
y = np.array(cBio['Overall Survival (Months)'], dtype=float)
X = cBio.drop('Overall Survival (Months)', axis=1)

# Integrating Pathway Commons Data

In [ ]:
path = "/content/PathwayCommons12.reactome.hgnc.sif.gz"


#specify compression type because the file is compressed
df = pd.read_csv(path, sep="\t", compression="gzip", header=None, names=["Source", "InteractionType", "Target"])

In [ ]:
df = df.drop(columns='InteractionType')

In [ ]:
df.head()

  Source    Target
0   A1CF   APOBEC1
1   A1CF   APOBEC2
2   A1CF  APOBEC3A
3   A1CF  APOBEC3B
4   A1CF  APOBEC3C

In [ ]:
all_nodes = sorted(list(set(df['Source']) | set(df['Target'])))
len(all_nodes)

12324

In [ ]:
#getting number of common nodes between pathway commons and newly merged cBio data
len(set(all_nodes) & set(X.columns))

9614

In [ ]:
#getting number of common nodes between pathway commons and newly merged cBio data
used_nodes = sorted(list(set(X.columns) & set(all_nodes)))
len(used_nodes)

9614

In [ ]:
# Filter rows in the DataFrame where the 'Source' column values are in 'used_nodes'
source_values = df['Source'].values
mask = np.isin(source_values, used_nodes)
df = df.loc[mask]

# Filter rows in the DataFrame where the 'Target' column values are in 'used_nodes'
source_values = df['Target'].values
mask = np.isin(source_values, used_nodes)
df = df.loc[mask]

# Reset the index of the DataFrame after filtering rows
df = df.reset_index(drop=True)

# Display the first two rows of the DataFrame 'X'
X.head(2)

,NUDT18,SHC3,NCRNA00112,FAM49B,FMO6P,BAT2L2,SIRT1,MSLNL,ATG4A,ESPN,...,SCARNA6,SNORD77,TLR10,GKN2,PCDHGB4,ZMAT5,AXIN2,LONRF1,KLHL10,C12orf36
TCGA-OR-A5J1-01,85.0144,97.5024,0.0,671.950,0.0,2428.43,462.056,0.0,385.687,20.1729,...,0.0000,0.0,12.0077,0.0,17.2911,913.535,547.55,363.112,1.9212,0.0
TCGA-OR-A5J2-01,165.8840,92.6050,0.0,812.911,0.0,5097.30,669.977,0.0,547.980,2.8184,...,0.4026,0.0,0.8053,0.0,268.9890,303.978,1793.32,592.672,0.0000,0.0

In [ ]:
len(set(df['Source']) | set(df['Target']))

9288

In [ ]:
# Get the unique values from the 'Source' and 'Target' columns and combine them into a set
columns_to_select = sorted(set(df['Source']).union(set(df['Target'])))

# Select the columns in 'X' that are present in 'columns_to_select'
X = X[columns_to_select]

# Display the first two rows of the updated 'X' DataFrame
X.head(2)

,A1CF,A2M,A4GNT,AAAS,AACS,AADAT,AAK1,AANAT,AARS,AARS2,...,ZP2,ZP3,ZP4,ZRANB1,ZRSR2,ZSCAN10,ZW10,ZWILCH,ZWINT,ZZZ3
TCGA-OR-A5J1-01,0.0,10373.70,0.0,2225.26,1266.090,121.0370,868.876,1.4409,3520.65,299.712,...,0.0,306.9160,0.0,2180.12,256.004,0.0000,253.602,183.958,146.974,596.062
TCGA-OR-A5J2-01,0.0,9844.91,0.0,1509.46,981.613,31.0025,1627.030,0.0000,5470.94,408.666,...,0.0,99.4255,0.0,2553.48,104.684,0.4026,270.165,264.125,438.464,801.637

# Creating Edge Index from Pathway commons

In [ ]:
!pip install torch-geometric

Collecting torch-geometric
  Downloading torch_geometric-2.3.1.tar.gz (661 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.6/661.6 kB 2.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (4.66.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (1.10.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (3.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (2.31.0)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (3.1.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (1.2.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch-geometric) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (2023.7.22)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->torch-geometric) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->torch-geometric) (3.2.0)
Building wheels for collected packages: torch-geometric
  Building wheel for torch-geometric (pyproject.toml) ... done
  Created wheel for torch-geometric: filename=torch_geometric-2.3.1-py3-none-any.whl size=910454 sha256=ef2d056066ce57a4bc7d05618b907d1dc306d5b78bdfce17cf6c3715a06e56b6
  Stored in directory: /root/.cache/pip/wheels/ac/dc/30/e2874821ff308ee67dcd7a66dbde912411e19e35a1addda028
Successfully built torch-geometric
Installing collected packages: torch-geometric
Successfully installed torch-geometric-2.3.1

In [ ]:
import torch

In [ ]:
source_nodes = df['Source'].tolist()
target_nodes = df['Target'].tolist()


#Create a dictionary to map each unique node to a unique index
node_to_index = {node: index for index, node in enumerate(X.columns)}

# Map the source and target nodes to their corresponding indices
source_indices = [node_to_index[node] for node in source_nodes]
target_indices = [node_to_index[node] for node in target_nodes]

In [ ]:
# Convert the source and target indices to a PyTorch tensor
edge_index = torch.tensor([source_indices, target_indices], dtype=torch.long)

In [ ]:
# Set the fixed index for splitting using 70:30 ratio
split_index = int(0.7 * X.shape[0])

# Split the data based on the fixed index
X_train = X[:split_index]
X_test = X[split_index:]
y_train = y[:split_index]
y_test = y[split_index:]

In [ ]:
X_train.shape, X_test.shape

((54, 9288), (24, 9288))

# Saving the integrated datasets

In [ ]:
X.to_csv('graph_idx.csv')

np.savetxt('graph_labels.csv', y, delimiter=',')

In [ ]:
# Save the tensor to a file
file_path = 'edge_index.pt'
torch.save(edge_index, file_path)

In [ ]:
import pandas as pd

# Save X_train to a CSV file
X_train.to_csv('X_train.csv')

# Save X_test to a CSV file
X_test.to_csv('X_test.csv')

# Save y_train to a CSV file
np.savetxt('y_train.csv', y_train, delimiter=',')

# Save y_test to a CSV file
np.savetxt('y_test.csv', y_test, delimiter=',')