<a href="https://colab.research.google.com/github/cannin/gsoc_2023_pytorch_pathway_commons/blob/main/Notebooks/breast_cancer_preprocesing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [ ]:
import pandas as pd

In [ ]:
!wget https://zenodo.org/record/8251328/files/data_clinical_patient.txt?download=1 -O data_clinical_patient.txt

--2023-08-28 13:40:39--  https://zenodo.org/record/8251328/files/data_clinical_patient.txt?download=1
Resolving zenodo.org (zenodo.org)... 188.185.124.72
Connecting to zenodo.org (zenodo.org)|188.185.124.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 337168 (329K) [text/plain]
Saving to: ‘data_clinical_patient.txt’

data_clinical_patie 100%[===================>] 329.27K   432KB/s    in 0.8s

2023-08-28 13:40:41 (432 KB/s) - ‘data_clinical_patient.txt’ saved [337168/337168]

In [ ]:
!wget https://zenodo.org/record/8251328/files/data_clinical_sample.txt?download=1 -O data_clinical_sample.txt

--2023-08-28 13:40:42--  https://zenodo.org/record/8251328/files/data_clinical_sample.txt?download=1
Resolving zenodo.org (zenodo.org)... 188.185.124.72
Connecting to zenodo.org (zenodo.org)|188.185.124.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 200366 (196K) [text/plain]
Saving to: ‘data_clinical_sample.txt’

data_clinical_sampl 100%[===================>] 195.67K   434KB/s    in 0.5s

2023-08-28 13:40:44 (434 KB/s) - ‘data_clinical_sample.txt’ saved [200366/200366]

In [ ]:
!wget https://zenodo.org/record/8251328/files/data_mrna_seq_v2_rsem.txt?download=1 -O data_mrna_seq_v2_rsem.txt

--2023-08-28 13:40:44--  https://zenodo.org/record/8251328/files/data_mrna_seq_v2_rsem.txt?download=1
Resolving zenodo.org (zenodo.org)... 188.185.124.72
Connecting to zenodo.org (zenodo.org)|188.185.124.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154654163 (147M) [text/plain]
Saving to: ‘data_mrna_seq_v2_rsem.txt’

data_mrna_seq_v2_rs 100%[===================>] 147.49M  1.57MB/s    in 2m 21s

2023-08-28 13:43:07 (1.04 MB/s) - ‘data_mrna_seq_v2_rsem.txt’ saved [154654163/154654163]

In [ ]:
!wget https://zenodo.org/record/8251328/files/PathwayCommons12.reactome.hgnc.sif.gz?download=1 -O PathwayCommons12.reactome.hgnc.sif.gz

--2023-08-28 13:43:07--  https://zenodo.org/record/8251328/files/PathwayCommons12.reactome.hgnc.sif.gz?download=1
Resolving zenodo.org (zenodo.org)... 188.185.124.72
Connecting to zenodo.org (zenodo.org)|188.185.124.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1231249 (1.2M) [application/octet-stream]
Saving to: ‘PathwayCommons12.reactome.hgnc.sif.gz’

PathwayCommons12.re 100%[===================>]   1.17M   358KB/s    in 3.4s

2023-08-28 13:43:12 (358 KB/s) - ‘PathwayCommons12.reactome.hgnc.sif.gz’ saved [1231249/1231249]

# Handling the cBIo Data

In [ ]:
data_sample = pd.read_csv("data_clinical_sample.txt", sep="\t")

In [ ]:
data_sample.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Neoplasm Histologic Grade,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,Sample Type,MSI MANTIS Score,MSIsensor Score,Somatic Status,TMB (nonsynonymous),Tissue Source Site
0,#Identifier to uniquely specify a patient.,A unique sample identifier.,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Numeric value to express the degree of abnorma...,Tissue prospective collection indicator.,Tissue retrospective collection indicator.,Tissue Source Site Code,Text term that describes the anatomic site of ...,Aneuploidy Score,"The type of sample (i.e., normal, primary, met...",MSI Score reported by MANTIS. The suggested th...,MSI Score reported by MSIsensor. The suggested...,Somatic Status,TMB (nonsynonymous),"A Tissue Source Site collects samples (tissue,..."
1,#STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,NUMBER,STRING,NUMBER,NUMBER,STRING,NUMBER,STRING
2,#1,1,1,1,1,1,1,1,1,1,1,1,9,9,9,1,1,1
3,PATIENT_ID,SAMPLE_ID,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,TUMOR_TYPE,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TISSUE_SOURCE_SITE_CODE,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,SOMATIC_STATUS,TMB_NONSYNONYMOUS,TISSUE_SOURCE_SITE
4,TCGA-3C-AAAU,TCGA-3C-AAAU-01,ILC,Breast Cancer,Breast Invasive Lobular Carcinoma,Infiltrating Lobular Carcinoma,NaN,No,Yes,3C,Breast,19,Primary,0.3319,0.55,Matched,0.8,Columbia University

In [ ]:
ds1 = data_sample.drop([0,1,2,3])
ds1.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Neoplasm Histologic Grade,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,Sample Type,MSI MANTIS Score,MSIsensor Score,Somatic Status,TMB (nonsynonymous),Tissue Source Site
4,TCGA-3C-AAAU,TCGA-3C-AAAU-01,ILC,Breast Cancer,Breast Invasive Lobular Carcinoma,Infiltrating Lobular Carcinoma,NaN,No,Yes,3C,Breast,19,Primary,0.3319,0.55,Matched,0.8,Columbia University
5,TCGA-3C-AALI,TCGA-3C-AALI-01,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Infiltrating Ductal Carcinoma,NaN,No,Yes,3C,Breast,22,Primary,0.3449,0.74,Matched,15.26666667,Columbia University
6,TCGA-3C-AALJ,TCGA-3C-AALJ-01,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Infiltrating Ductal Carcinoma,NaN,No,Yes,3C,Breast,13,Primary,0.3266,0.31,Matched,0.933333333,Columbia University
7,TCGA-3C-AALK,TCGA-3C-AALK-01,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Infiltrating Ductal Carcinoma,NaN,No,Yes,3C,Breast,4,Primary,0.3218,0.03,Matched,1.5,Columbia University
8,TCGA-4H-AAAK,TCGA-4H-AAAK-01,ILC,Breast Cancer,Breast Invasive Lobular Carcinoma,Infiltrating Lobular Carcinoma,NaN,Yes,No,4H,Breast,7,Primary,0.3411,0.01,Matched,0.7,"Proteogenex, Inc."

In [ ]:
ds1.shape

(1084, 18)

In [ ]:
ds1.isnull().sum()

#Patient Identifier                             0
Sample Identifier                               0
Oncotree Code                                   0
Cancer Type                                     0
Cancer Type Detailed                            0
Tumor Type                                      0
Neoplasm Histologic Grade                    1084
Tissue Prospective Collection Indicator         4
Tissue Retrospective Collection Indicator       4
Tissue Source Site Code                         0
Tumor Disease Anatomic Site                     0
Aneuploidy Score                               43
Sample Type                                     0
MSI MANTIS Score                               50
MSIsensor Score                                 9
Somatic Status                                  0
TMB (nonsynonymous)                            18
Tissue Source Site                              0
dtype: int64

In [ ]:
cleaned_ds = ds1.dropna(axis=1, how='all')
cleaned_ds.isnull().sum()

#Patient Identifier                           0
Sample Identifier                             0
Oncotree Code                                 0
Cancer Type                                   0
Cancer Type Detailed                          0
Tumor Type                                    0
Tissue Prospective Collection Indicator       4
Tissue Retrospective Collection Indicator     4
Tissue Source Site Code                       0
Tumor Disease Anatomic Site                   0
Aneuploidy Score                             43
Sample Type                                   0
MSI MANTIS Score                             50
MSIsensor Score                               9
Somatic Status                                0
TMB (nonsynonymous)                          18
Tissue Source Site                            0
dtype: int64

In [ ]:
cleaned_ds = cleaned_ds.fillna(method='ffill')

In [ ]:
cleaned_ds = cleaned_ds.drop(columns='Cancer Type')

In [ ]:
data_patient = pd.read_csv("data_clinical_patient.txt", sep="\t")

In [ ]:
dcp = data_patient.drop([0,1,2,3])
dcp.head()

,#Patient Identifier,Subtype,TCGA PanCanAtlas Cancer Type Acronym,Other Patient ID,Diagnosis Age,Sex,Neoplasm Disease Stage American Joint Committee on Cancer Code,American Joint Committee on Cancer Publication Version Type,Last Communication Contact from Initial Pathologic Diagnosis Date,Birth from Initial Pathologic Diagnosis Date,...,Patient Weight,In PanCan Pathway Analysis,Overall Survival Status,Overall Survival (Months),Disease-specific Survival status,Months of disease-specific survival,Disease Free Status,Disease Free (Months),Progression Free Status,Progress Free Survival (Months)
4,TCGA-3C-AAAU,BRCA_LumA,BRCA,6E7D5EC6-A469-467C-B748-237353C23416,55,Female,STAGE X,6TH,4047,-20211,...,NaN,Yes,0:LIVING,133.0505967,0:ALIVE OR DEAD TUMOR FREE,133.0505967,1:Recurred/Progressed,59.44044449,1:PROGRESSION,59.44044449
5,TCGA-3C-AALI,BRCA_Her2,BRCA,55262FCB-1B01-4480-B322-36570430C917,50,Female,STAGE IIB,6TH,4005,-18538,...,NaN,Yes,0:LIVING,131.6697899,0:ALIVE OR DEAD TUMOR FREE,131.6697899,0:DiseaseFree,131.6697899,0:CENSORED,131.6697899
6,TCGA-3C-AALJ,BRCA_LumB,BRCA,427D0648-3F77-4FFC-B52C-89855426D647,62,Female,STAGE IIB,7TH,1474,-22848,...,NaN,Yes,0:LIVING,48.45974291,0:ALIVE OR DEAD TUMOR FREE,48.45974291,0:DiseaseFree,48.45974291,0:CENSORED,48.45974291
7,TCGA-3C-AALK,BRCA_LumA,BRCA,C31900A4-5DCD-4022-97AC-638E86E889E4,52,Female,STAGE IA,7TH,1448,-19074,...,NaN,Yes,0:LIVING,47.60495775,0:ALIVE OR DEAD TUMOR FREE,47.60495775,NaN,NaN,0:CENSORED,47.60495775
8,TCGA-4H-AAAK,BRCA_LumA,BRCA,6623FC5E-00BE-4476-967A-CBD55F676EA6,50,Female,STAGE IIIA,7TH,348,-18371,...,NaN,Yes,0:LIVING,11.44097051,0:ALIVE OR DEAD TUMOR FREE,11.44097051,0:DiseaseFree,11.44097051,0:CENSORED,11.44097051

In [ ]:
dcp.isnull().sum()

#Patient Identifier                                                                               0
Subtype                                                                                         103
TCGA PanCanAtlas Cancer Type Acronym                                                              0
Other Patient ID                                                                                  0
Diagnosis Age                                                                                     0
Sex                                                                                               0
Neoplasm Disease Stage American Joint Committee on Cancer Code                                    5
American Joint Committee on Cancer Publication Version Type                                     140
Last Communication Contact from Initial Pathologic Diagnosis Date                               104
Birth from Initial Pathologic Diagnosis Date                                                     15
Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value                            0
Ethnicity Category                                                                              169
Form completion date                                                                              0
Neoadjuvant Therapy Type Administered Prior To Resection Text                                     1
ICD-10 Classification                                                                             0
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code       0
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code            0
Informed consent verified                                                                         0
New Neoplasm Event Post Initial Therapy Indicator                                               199
American Joint Committee on Cancer Metastasis Stage Code                                          0
Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code                         0
American Joint Committee on Cancer Tumor Stage Code                                               0
Person Neoplasm Cancer Status                                                                   123
Primary Lymph Node Presentation Assessment                                                      364
Prior Diagnosis                                                                                   1
Race Category                                                                                    90
Radiation Therapy                                                                               101
Patient Weight                                                                                 1084
In PanCan Pathway Analysis                                                                        0
Overall Survival Status                                                                           0
Overall Survival (Months)                                                                         0
Disease-specific Survival status                                                                 20
Months of disease-specific survival                                                               2
Disease Free Status                                                                             142
Disease Free (Months)                                                                           143
Progression Free Status                                                                           1
Progress Free Survival (Months)                                                                   2
dtype: int64

In [ ]:
dcp = dcp.dropna(how='any', axis=1)

In [ ]:
merged_df = pd.merge(cleaned_ds, dcp, on='#Patient Identifier')

In [ ]:
merged_df.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type Detailed,Tumor Type,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,...,ICD-10 Classification,"International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code","International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code",Informed consent verified,American Joint Committee on Cancer Metastasis Stage Code,Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code,American Joint Committee on Cancer Tumor Stage Code,In PanCan Pathway Analysis,Overall Survival Status,Overall Survival (Months)
0,TCGA-3C-AAAU,TCGA-3C-AAAU-01,ILC,Breast Invasive Lobular Carcinoma,Infiltrating Lobular Carcinoma,No,Yes,3C,Breast,19,...,C50.9,8520/3,C50.9,Yes,MX,NX,TX,Yes,0:LIVING,133.0505967
1,TCGA-3C-AALI,TCGA-3C-AALI-01,IDC,Breast Invasive Ductal Carcinoma,Infiltrating Ductal Carcinoma,No,Yes,3C,Breast,22,...,C50.9,8500/3,C50.9,Yes,M0,N1A,T2,Yes,0:LIVING,131.6697899
2,TCGA-3C-AALJ,TCGA-3C-AALJ-01,IDC,Breast Invasive Ductal Carcinoma,Infiltrating Ductal Carcinoma,No,Yes,3C,Breast,13,...,C50.9,8500/3,C50.9,Yes,M0,N1A,T2,Yes,0:LIVING,48.45974291
3,TCGA-3C-AALK,TCGA-3C-AALK-01,IDC,Breast Invasive Ductal Carcinoma,Infiltrating Ductal Carcinoma,No,Yes,3C,Breast,4,...,C50.9,8500/3,C50.9,Yes,M0,N0 (I+),T1C,Yes,0:LIVING,47.60495775
4,TCGA-4H-AAAK,TCGA-4H-AAAK-01,ILC,Breast Invasive Lobular Carcinoma,Infiltrating Lobular Carcinoma,Yes,No,4H,Breast,7,...,C50.9,8520/3,C50.9,Yes,M0,N2A,T2,Yes,0:LIVING,11.44097051

In [ ]:
merged_df.columns

Index(['#Patient Identifier', 'Sample Identifier', 'Oncotree Code',
       'Cancer Type Detailed', 'Tumor Type',
       'Tissue Prospective Collection Indicator',
       'Tissue Retrospective Collection Indicator', 'Tissue Source Site Code',
       'Tumor Disease Anatomic Site', 'Aneuploidy Score', 'Sample Type',
       'MSI MANTIS Score', 'MSIsensor Score', 'Somatic Status',
       'TMB (nonsynonymous)', 'Tissue Source Site',
       'TCGA PanCanAtlas Cancer Type Acronym', 'Other Patient ID',
       'Diagnosis Age', 'Sex',
       'Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value',
       'Form completion date', 'ICD-10 Classification',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
       'Informed consent verified',
       'American Joint Committee on Cancer Metastasis Stage Code',
       'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code',
       'American Joint Committee on Cancer Tumor Stage Code',
       'In PanCan Pathway Analysis', 'Overall Survival Status',
       'Overall Survival (Months)'],
      dtype='object')

In [ ]:
# Assuming your DataFrame is named 'df'
columns_to_keep = ['#Patient Identifier', 'Sample Identifier', 'Overall Survival (Months)']
used_df = merged_df[columns_to_keep]

In [ ]:
used_df.head()

  #Patient Identifier Sample Identifier Overall Survival (Months)
0        TCGA-3C-AAAU   TCGA-3C-AAAU-01               133.0505967
1        TCGA-3C-AALI   TCGA-3C-AALI-01               131.6697899
2        TCGA-3C-AALJ   TCGA-3C-AALJ-01               48.45974291
3        TCGA-3C-AALK   TCGA-3C-AALK-01               47.60495775
4        TCGA-4H-AAAK   TCGA-4H-AAAK-01               11.44097051

In [ ]:
used_df.shape

(1084, 3)

In [ ]:
df = pd.read_csv("data_mrna_seq_v2_rsem.txt", sep="\t")

In [ ]:
patients = df.copy()
patients.head()

,Hugo_Symbol,Entrez_Gene_Id,TCGA-3C-AAAU-01,TCGA-3C-AALI-01,TCGA-3C-AALJ-01,TCGA-3C-AALK-01,TCGA-4H-AAAK-01,TCGA-5L-AAT0-01,TCGA-5T-A9QA-01,TCGA-A1-A0SB-01,...,TCGA-UL-AAZ6-01,TCGA-UU-A93S-01,TCGA-V7-A7HQ-01,TCGA-W8-A86G-01,TCGA-WT-AB41-01,TCGA-WT-AB44-01,TCGA-XX-A899-01,TCGA-XX-A89A-01,TCGA-Z7-A8R5-01,TCGA-Z7-A8R6-01
0,NaN,100130426,0.0000,0.0000,0.9066,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,NaN,100133144,16.3644,9.2659,11.6228,12.0894,6.8468,3.9889,1.4644,15.3396,...,0.3992,4.3126,0.0000,5.5624,0.0000,0.0000,14.3858,22.3240,2.2638,6.8865
2,UBE2Q2P2,100134869,12.9316,17.3790,9.2294,11.0799,14.4298,13.6090,8.9958,14.3935,...,14.3720,10.8828,3.0792,14.3711,6.3091,3.2580,21.4409,27.2744,7.2933,24.7795
3,HMGB1P1,10357,52.1503,69.7553,154.2970,143.8640,84.2128,114.2570,107.5630,116.3870,...,135.6240,136.1290,29.9974,128.3150,53.6278,42.2643,137.7760,64.1427,85.0461,167.5510
4,NaN,10431,408.0760,563.8930,1360.8300,865.5360,766.3830,807.7430,1420.5000,657.2810,...,1570.1400,2886.4000,1721.8800,697.6740,1245.2700,1877.4200,652.7560,722.7210,1140.2800,1003.5700

In [ ]:
patients = patients.drop('Entrez_Gene_Id', axis=1)

In [ ]:
patients.shape

(20531, 1083)

In [ ]:
patients.isnull().sum()

Hugo_Symbol        13
TCGA-3C-AAAU-01     0
TCGA-3C-AALI-01     0
TCGA-3C-AALJ-01     0
TCGA-3C-AALK-01     0
                   ..
TCGA-WT-AB44-01     0
TCGA-XX-A899-01     0
TCGA-XX-A89A-01     0
TCGA-Z7-A8R5-01     0
TCGA-Z7-A8R6-01     0
Length: 1083, dtype: int64

In [ ]:
patients = patients.dropna()

In [ ]:
identifiers = patients['Hugo_Symbol'].unique()
print(len(identifiers))

20511

In [ ]:
# Check for duplicate 'Hugo_Symbol' values
duplicates = patients['Hugo_Symbol'].duplicated(keep='last')

# Drop rows with duplicate 'Hugo_Symbol' or same symbol as the previous row
new_df = patients[~duplicates]

# Verify the updated DataFrame shape
print(new_df.shape)

(20511, 1083)

In [ ]:
new_df.shape

(20511, 1083)

In [ ]:
new_df_transposed = new_df.set_index('Hugo_Symbol').transpose()
new_df_transposed.head()

Hugo_Symbol,UBE2Q2P2,HMGB1P1,RNU12-2P,SSX9P,EZHIP,EFCAB8,SRP14P1,TRIM75P,SPATA31B1P,REXO1L6P,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
TCGA-3C-AAAU-01,12.9316,52.1503,0.0000,0.0000,1.7233,0.3447,4.1359,0.6893,0.0,0.0,...,415.824,931.957,129.5920,1007.780,1658.500,258.4940,1208.370,3507.25,1894.930,1180.460
TCGA-3C-AALI-01,17.3790,69.7553,1.0875,0.5438,144.1000,4.8940,1.6313,0.5438,0.0,0.0,...,1161.330,965.198,59.8151,448.613,1343.120,198.4770,603.589,5504.62,1318.650,406.743
TCGA-3C-AALJ-01,9.2294,154.2970,0.0000,0.0000,0.0000,2.7199,2.7199,0.0000,0.0,0.0,...,305.422,2531.280,35.3581,533.998,768.812,331.8220,532.185,5458.75,942.883,509.519
TCGA-3C-AALK-01,11.0799,143.8640,0.4137,0.0000,0.0000,2.0687,4.5511,0.0000,0.0,0.0,...,394.506,668.597,55.0269,437.733,863.881,175.4240,607.365,5691.35,781.134,700.869
TCGA-4H-AAAK-01,14.4298,84.2128,0.4255,0.0000,0.4255,2.9787,2.9787,0.0000,0.0,0.0,...,405.711,674.468,48.9362,424.255,1049.790,14.0426,775.745,4041.70,831.915,881.702

In [ ]:
# Merge the datasets based on the patient identifiers
patient_df = pd.merge(used_df, new_df_transposed, left_on='Sample Identifier', right_index=True)

In [ ]:
patient_df.shape

(1082, 20514)

In [ ]:
patient_df.head()

,#Patient Identifier,Sample Identifier,Overall Survival (Months),UBE2Q2P2,HMGB1P1,RNU12-2P,SSX9P,EZHIP,EFCAB8,SRP14P1,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,TCGA-3C-AAAU,TCGA-3C-AAAU-01,133.0505967,12.9316,52.1503,0.0000,0.0000,1.7233,0.3447,4.1359,...,415.824,931.957,129.5920,1007.780,1658.500,258.4940,1208.370,3507.25,1894.930,1180.460
1,TCGA-3C-AALI,TCGA-3C-AALI-01,131.6697899,17.3790,69.7553,1.0875,0.5438,144.1000,4.8940,1.6313,...,1161.330,965.198,59.8151,448.613,1343.120,198.4770,603.589,5504.62,1318.650,406.743
2,TCGA-3C-AALJ,TCGA-3C-AALJ-01,48.45974291,9.2294,154.2970,0.0000,0.0000,0.0000,2.7199,2.7199,...,305.422,2531.280,35.3581,533.998,768.812,331.8220,532.185,5458.75,942.883,509.519
3,TCGA-3C-AALK,TCGA-3C-AALK-01,47.60495775,11.0799,143.8640,0.4137,0.0000,0.0000,2.0687,4.5511,...,394.506,668.597,55.0269,437.733,863.881,175.4240,607.365,5691.35,781.134,700.869
4,TCGA-4H-AAAK,TCGA-4H-AAAK-01,11.44097051,14.4298,84.2128,0.4255,0.0000,0.4255,2.9787,2.9787,...,405.711,674.468,48.9362,424.255,1049.790,14.0426,775.745,4041.70,831.915,881.702

In [ ]:
patient_df = patient_df.drop('#Patient Identifier', axis=1)

In [ ]:
patient_df.set_index('Sample Identifier')

,Overall Survival (Months),UBE2Q2P2,HMGB1P1,RNU12-2P,SSX9P,EZHIP,EFCAB8,SRP14P1,TRIM75P,SPATA31B1P,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
Sample Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-3C-AAAU-01,133.0505967,12.9316,52.1503,0.0000,0.0000,1.7233,0.3447,4.1359,0.6893,0.0,...,415.824,931.957,129.5920,1007.780,1658.500,258.4940,1208.370,3507.25,1894.930,1180.460
TCGA-3C-AALI-01,131.6697899,17.3790,69.7553,1.0875,0.5438,144.1000,4.8940,1.6313,0.5438,0.0,...,1161.330,965.198,59.8151,448.613,1343.120,198.4770,603.589,5504.62,1318.650,406.743
TCGA-3C-AALJ-01,48.45974291,9.2294,154.2970,0.0000,0.0000,0.0000,2.7199,2.7199,0.0000,0.0,...,305.422,2531.280,35.3581,533.998,768.812,331.8220,532.185,5458.75,942.883,509.519
TCGA-3C-AALK-01,47.60495775,11.0799,143.8640,0.4137,0.0000,0.0000,2.0687,4.5511,0.0000,0.0,...,394.506,668.597,55.0269,437.733,863.881,175.4240,607.365,5691.35,781.134,700.869
TCGA-4H-AAAK-01,11.44097051,14.4298,84.2128,0.4255,0.0000,0.4255,2.9787,2.9787,0.0000,0.0,...,405.711,674.468,48.9362,424.255,1049.790,14.0426,775.745,4041.70,831.915,881.702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-WT-AB44-01,29.02981885,3.2580,42.2643,4.0725,0.0000,0.8145,3.2580,4.0725,0.0000,0.0,...,150.014,180.819,24.4349,243.535,772.959,98.5543,315.211,10937.10,800.652,443.087
TCGA-XX-A899-01,15.3532564,21.4409,137.7760,2.7559,0.0000,2.7559,1.5748,6.6929,0.0000,0.0,...,456.047,457.087,70.8661,643.701,1266.540,21.2598,688.189,5118.11,1933.860,670.079
TCGA-XX-A89A-01,16.0436598,27.2744,64.1427,0.4724,0.0000,17.4776,1.4171,6.6131,0.0000,0.0,...,530.198,694.379,48.6538,341.521,1375.530,164.3840,746.812,5477.56,1437.410,953.708
TCGA-Z7-A8R5-01,108.0645692,7.2933,85.0461,0.5973,0.0000,0.0000,0.5973,4.1812,0.0000,0.0,...,173.109,258.639,32.2552,248.484,796.225,51.9667,505.928,6675.63,754.413,750.829
TCGA-Z7-A8R6-01,107.0454022,24.7795,167.5510,0.3480,0.0000,0.3480,2.7838,4.8717,0.3480,0.0,...,521.169,2435.840,34.4498,389.735,947.890,139.5390,573.467,3402.52,564.419,462.114

In [ ]:
patient_df.to_csv('Brca_patients.csv', index= False)

In [ ]:
brc = pd.read_csv('/content/Brca_patients.csv')

In [ ]:
brc = brc.set_index('Sample Identifier')
brc.index.name = None
brc.head(2)

,Overall Survival (Months),UBE2Q2P2,HMGB1P1,RNU12-2P,SSX9P,EZHIP,EFCAB8,SRP14P1,TRIM75P,SPATA31B1P,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
TCGA-3C-AAAU-01,133.050597,12.9316,52.1503,0.0000,0.0000,1.7233,0.3447,4.1359,0.6893,0.0,...,415.824,931.957,129.5920,1007.780,1658.50,258.494,1208.370,3507.25,1894.93,1180.460
TCGA-3C-AALI-01,131.669790,17.3790,69.7553,1.0875,0.5438,144.1000,4.8940,1.6313,0.5438,0.0,...,1161.330,965.198,59.8151,448.613,1343.12,198.477,603.589,5504.62,1318.65,406.743

In [ ]:
import numpy as np

#splitting the created dataset to features and lables
y = np.array(brc['Overall Survival (Months)'], dtype=float)
X = brc.drop('Overall Survival (Months)', axis=1)

# Integrating Pathway Commons Data

In [ ]:
path = "PathwayCommons12.reactome.hgnc.sif.gz"


#specify compression type because the file is compressed
df = pd.read_csv(path, sep="\t", compression="gzip", header=None, names=["Source", "InteractionType", "Target"])

In [ ]:
df = df.drop(columns='InteractionType')

In [ ]:
df.head()

  Source    Target
0   A1CF   APOBEC1
1   A1CF   APOBEC2
2   A1CF  APOBEC3A
3   A1CF  APOBEC3B
4   A1CF  APOBEC3C

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_0, *['Target'], **{})
chart

In [ ]:
all_nodes = sorted(list(set(df['Source']) | set(df['Target'])))
len(all_nodes)

12324

In [ ]:
#getting number of common nodes between pathway commons and newly merged cBio data
used_nodes = sorted(list(set(X.columns) & set(all_nodes)))
len(used_nodes)

9614

In [ ]:
# Filter rows in the DataFrame where the 'Source' column values are in 'used_nodes'
source_values = df['Source'].values
mask = np.isin(source_values, used_nodes)
df = df.loc[mask]

# Filter rows in the DataFrame where the 'Target' column values are in 'used_nodes'
source_values = df['Target'].values
mask = np.isin(source_values, used_nodes)
df = df.loc[mask]

# Reset the index of the DataFrame after filtering rows
df = df.reset_index(drop=True)

# Display the first two rows of the DataFrame 'X'
X.head(2)

,UBE2Q2P2,HMGB1P1,RNU12-2P,SSX9P,EZHIP,EFCAB8,SRP14P1,TRIM75P,SPATA31B1P,REXO1L6P,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
TCGA-3C-AAAU-01,12.9316,52.1503,0.0000,0.0000,1.7233,0.3447,4.1359,0.6893,0.0,0.0,...,415.824,931.957,129.5920,1007.780,1658.50,258.494,1208.370,3507.25,1894.93,1180.460
TCGA-3C-AALI-01,17.3790,69.7553,1.0875,0.5438,144.1000,4.8940,1.6313,0.5438,0.0,0.0,...,1161.330,965.198,59.8151,448.613,1343.12,198.477,603.589,5504.62,1318.65,406.743

In [ ]:
len(set(df['Source']) | set(df['Target']))

9288

In [ ]:
# Get the unique values from the 'Source' and 'Target' columns and combine them into a set
columns_to_select = sorted(set(df['Source']).union(set(df['Target'])))

# Select the columns in 'X' that are present in 'columns_to_select'
X = X[columns_to_select]

# Display the first two rows of the updated 'X' DataFrame
X.head(2)

,A1CF,A2M,A4GNT,AAAS,AACS,AADAT,AAK1,AANAT,AARS,AARS2,...,ZP2,ZP3,ZP4,ZRANB1,ZRSR2,ZSCAN10,ZW10,ZWILCH,ZWINT,ZZZ3
TCGA-3C-AAAU-01,0.0,5798.37,8.6165,649.337,1087.400,5.5145,517.333,0.3447,4409.56,689.897,...,0.0000,411.791,0.0000,879.225,421.862,2.7573,430.824,415.824,931.957,1180.460
TCGA-3C-AALI-01,0.0,7571.98,0.5438,887.983,836.324,24.4698,848.287,2.1751,4570.96,472.501,...,4.3502,439.222,0.5438,566.068,349.647,0.0000,340.402,1161.330,965.198,406.743

# Creating Edge Index from Pathway commons

In [ ]:
!pip install torch-geometric

Collecting torch-geometric
  Downloading torch_geometric-2.3.1.tar.gz (661 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.6/661.6 kB 6.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (4.66.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (1.10.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (3.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (2.31.0)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (3.1.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (1.2.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch-geometric) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (2023.7.22)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->torch-geometric) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->torch-geometric) (3.2.0)
Building wheels for collected packages: torch-geometric
  Building wheel for torch-geometric (pyproject.toml) ... done
  Created wheel for torch-geometric: filename=torch_geometric-2.3.1-py3-none-any.whl size=910454 sha256=4fa35e8f5f64c58834dfbcc3a4d0e8a050c398abebd9e8972f9392284ca5389a
  Stored in directory: /root/.cache/pip/wheels/ac/dc/30/e2874821ff308ee67dcd7a66dbde912411e19e35a1addda028
Successfully built torch-geometric
Installing collected packages: torch-geometric
Successfully installed torch-geometric-2.3.1

In [ ]:
import torch

In [ ]:
source_nodes = df['Source'].tolist()
target_nodes = df['Target'].tolist()


#Create a dictionary to map each unique node to a unique index
node_to_index = {node: index for index, node in enumerate(X.columns)}

# Map the source and target nodes to their corresponding indices
source_indices = [node_to_index[node] for node in source_nodes]
target_indices = [node_to_index[node] for node in target_nodes]

In [ ]:
# Convert the source and target indices to a PyTorch tensor
edge_index = torch.tensor([source_indices, target_indices], dtype=torch.long)

In [ ]:
X.shape, y.shape

((1082, 9288), (1082,))

In [ ]:
edge_index.shape

torch.Size([2, 271771])

In [ ]:
# Set the fixed indices for splitting using 60:20:20 ratio
train_index = int(0.6 * X.shape[0])
val_index = int(0.6 * X.shape[0]) + int(0.2 * X.shape[0])

# Split the data into train, validation, and test sets
X_train = X[:train_index]
X_val = X[train_index:val_index]
X_test = X[val_index:]
y_train = y[:train_index]
y_val = y[train_index:val_index]
y_test = y[val_index:]

In [ ]:
X_train.shape, X_test.shape, X_val.shape

((649, 9288), (217, 9288), (216, 9288))

In [ ]:
y_train.shape, y_test.shape, y_val.shape

((649,), (217,), (216,))

#Saving the integrated datasets

In [ ]:
X.to_csv('graph_idx.csv')

np.savetxt('graph_labels.csv', y, delimiter=',')

In [ ]:
# Save the tensor to a file
file_path = 'edge_index.pt'
torch.save(edge_index, file_path)

In [ ]:
import pandas as pd

# Save X_train to a CSV file
X_train.to_csv('X_train.csv')

# Save X_test to a CSV file
X_test.to_csv('X_test.csv')

# Save X_val to a CSV file
X_val.to_csv('X_val.csv')

# Save X_val to a CSV file
np.savetxt('y_val.csv', y_val, delimiter=',')


# Save y_train to a CSV file
np.savetxt('y_train.csv', y_train, delimiter=',')

# Save y_test to a CSV file
np.savetxt('y_test.csv', y_test, delimiter=',')